name: auth_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  # Навігація
  go_router: ^16.0.0
  
  # Шрифти (щоб було як в дизайні, схоже на Inter)
  google_fonts: ^6.1.0
  
  # Робота з SVG (для іконок Google/Facebook)
  flutter_svg: ^2.0.9
  
  # Для зручного верстання (опціонально, але корисно)
  gap: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/